### ISSUE TITLE
undefined method 'stat' for File:Class with Crystal 0.25.0 [7fb783f7a]

### ISSUE THREAD

**Issue by timkrins** [amberframework/teeplate#4]
Just following the Amber Get Started guide and coming up against some issues.

`lib/teeplate/src/lib/file_tree/macros/directory.cr:33: undefined method 'stat' for File:Class`

Switched repo in `shard.yml` to mosop/teeplate and no error.

(error is due to Crystal File API change)

**Comment by timkrins** [comment]
Ah, I'm caught up now - https://github.com/amberframework/amber/pull/826

**Comment by faustinoaq** [comment]
Fixed! :+1:
